const { and } = require('sequelize');
const {Exercise} = require ('../models');

const exercisedata = [
    {
        name: 'Tricep dips',
        group: 'Arms',
        muscle: 'Tricep branchii',
        equipment: 'None',
        instructions: 'Stand facing away from a bench, grab it with both hands at shoulder-width. Extend your legs out in front of you. Slowly lower your body by flexing at the elbows until your arm at forearm create a 90 degree angle. Using your triceps, lift yourself back to the starting position.',
        difficulty: 'Intermidiate',
        images: 'tricep-dips-exercise-illustration.jpg',
        description: 'Tricep dip workout',
        group_id: 3,
        routine_id: 1
    },
    {
        name: 'Bicep curls',
        group: 'Arms',
        muscle: 'Biceps brachii, brachialis and brachioradialis',
        equipment: 'Dumbbell or machine',
        instructions: 'To do a biceps curl with a dumbbell, hold a dumbbell with your palm facing upward. Slowly curl the weight up by bending your elbow, keeping your elbow close to your body. Then slowly lower the weight to the starting position.',
        difficulty: 'Beginner',
        images: 'inner-bicep-curl-benefits.jpg',
        description: 'Bicep curl workout',
        group_id: 3,
        routine_id: 1
    },
    {
        name: 'Tricep pushdown',
        group: 'Arms',
        muscle: 'Tricep pushdowns target the medial and lateral heads of the triceps',
        equipment: 'Cable machine',
        instructions: 'Attach a rope attachment or horizontal bar to the cable machine. Face the cable machine with your feet slightly apart. Brace your abs and tuck your elbows at your sides. Make sure that your chest is out and the shoulder blades are together. Slightly bend forward too. Inhale. Push the attachment down until your elbows are fully extended but not locked in the joint. As you push the bar down, exhale. Slowly bring the attachment back up and inhale as you do so.',
        difficulty: 'Beginner',
        images: '',
        description: 'Tricep pushdown workout',
        group_id: 3,
        routine_id: 2,
    },
    {
        name: 'Hammer curls',
        group: 'Arms',
        muscle: 'Bicep brachii, brachialis, and brachioradialis',
        equipment: 'Dumbbells',
        instructions: 'While keeping your upper arms still, squeeze your bicep and bend your elbows until your lower arms touch your upper arms. The dumbbells should finish very close to your shoulders without actually touching your shoulders. Squeeze your biceps and pause for a few seconds at the top of the movement',
        difficulty: 'Intermidiate',
        images: '',
        description: 'Hammer curl workout',
        group_id: 3,
        routine_id: 2,
    },
    {
        name: 'Rear delt fly',
        group: 'Arms & Back',
        muscle: 'Posterior deltoid, & upper back',
        equipment: 'Dumbbells',
        instructions: 'Bend from the hips with the dumbbells hanging on both sides. Begin to lift the dumbbells so they are at a level that is slightly higher than your shoulders. Slowly, lower to starting position.',
        difficulty: 'Advanced',
        images: '',
        description: 'Rear delt fly workout',
        group_id: 3,
        routine_id: 2,
    },
    {
        name: 'Leg press',
        group: 'Legs',
        muscle: 'Quadripcap, gluteal, hamstring, and calf',
        equipment: 'Weight machine',      
        instructions: 'To start, sit with your back against a padded backrest and your feet on two large footrests. Your knees are bent to start the exercise. To move the weight, you must straighten your legs and then return them to the bent position.',
        difficulty: 'Beginner',
        images: '',
        description: 'Leg press workout',
        group_id: 5,
        routine_id: 1,
    },
    {
        name: 'Lunges',
        group: 'Legs',
        muscle: 'Gluteal, hamstring, quadricep, and calf',
        equipment: 'Dumbbells or none',      
        instructions: 'Stand with your feet hip-width apart, keep your back straight, your shoulders back, and your abs tight. Take a step forward and slowly bend both knees, until your back knee is just above the floor. Stand back up and repeat the movement. Alternate legs until the set is complete',
        difficulty: 'Intermidiate',
        images: '',
        description: 'Lunge workout',
        group_id: 5,
        routine_id: 2,
    },
    {
        name: 'Crunches',
        group: 'Abdominals',
        muscle: 'Abdominals and Obliques',
        equipment: 'none',
        instructions: 'Lie down on the mat, keep your knees bent, your back and feet flat, and your hands supporting your head. 2. Lift your shoulders, squeeze your abdominal muscles and hold for 1 to 2 seconds.',
        difficulty: 'Intermediate',
        images: '',
        description: 'Crunches workout',
        group_id: 6,
        routine_id: 1,
    },
    {
        name: 'Russian twists',
        group: 'Abdominals',
        muscle: 'Abdominals and Obliques',
        equipment: 'none',
        instructions: 'You will rotate your torso from side to side while sitting in an upright position with your feet lifted off the ground.',
        difficulty: 'Advanced',
        images: '',
        description: 'Russian twist workout',
        group_id: 6,
        routine_id: 2,
    },
    {
        name: 'Benchpress',
        group: 'Chest & Shoulder',
        muscle: 'Pectoral and shoulder muscles',
        equipment: 'Bench with barbell',
        instructions: 'Person lays supine on the bench, knees bent and feet flat on the floor. Grip the bar (grip can vary depending on goal) and un-rack bar. Lower the bar to the chest (around nipple level) Press the bar upward until the arms are fully extended, keep the feet on the floor.',
        difficulty: 'Intermediate',
        images: '',
        description: 'Benchpress workout',
        group_id: 1,
        routine_id: 1
    },
    {
        name: 'Push Ups',
        group: 'Chest, Arms, & Core',
        muscle: 'Pectorals, deltoid, tricep, and abdominals',
        equipment: 'none',
        instructions: 'From a prone position, the hands are placed under the shoulders with the elbows extended. Keeping the back and legs straight with the toes touching the ground. The body is lowered until the upper arm is parallel to the ground. Then reverse the movement and raise the body until arm is extended.',
        difficulty: 'Intermediate',
        images: '',
        description: 'Push up workout',
        group_id: 2,
        routine_id: 2
    },
    {
        name: 'Seated row',
        group: 'Back',
        muscle: 'Latissimus dorsi',
        equipment: 'Seated row machine',
        instructions: 'You should be sitting straight upright with your shoulders back. This is the starting position. Keeping your body in position, pull the handle into your stomach. Pull your shoulder blades back, squeeze, pause, and then slowly lower the weight back to the starting position.',
        difficulty: 'Intermediate',
        images: '',
        description: 'Seated row workout',
        group_id: 4,
        routine_id: 1,
    },
    {
        name: 'Pull ups',
        group: 'Back and Arms',
        muscle: 'Latissimus dorsi, trapezius, biceps, and triceps',
        equipment: 'Pull up bar',
        instructions: 'Step 1: Grab the pull-up bar with a 1-1.5x shoulder width grip, palms facing away from you. Step 2: Pull the body upward driving the chest toward the bar/handles until the arms/elbows are packed into the side of the body. Step 3: Reverse the pattern and return to starting position',
        difficulty: 'Advanced',
        images: '',
        description: 'Pull up workout',
        group_id: 4,
        routine_id: 2
    },
    {
        name: 'Shoulder Press',
        group: 'Shoulders',
        muscle: 'Deltoids, triceps, and trapezius',
        equipment: 'Dumbbells',
        instructions: 'Taking a dumbbell in each hand, stand shoulder width apart with the hips and spine in a neutral position. Lift the dumbbells so that they are positioned in between your shoulders and ears, palms facing forward. Engage your core and glutes and extend your arms to press the dumbbells above your head.',
        difficulty: 'Intermediate',
        images: '',
        description: 'Shoulder press workout',
        group_id: 1,
        routine_id: 1,
    },
    {
        name: 'Renegade Row',
        group: 'Shoulders',
        muscle: 'Triceps, trapezius, abdominals, obliques, and rhomboids',
        equipment: 'Dumbbells',
        instructions: 'Drive your right arm through the dumbbell into the floor, stiffen your entire body, and row the left dumbbell up and to the side of your rib cage—your elbow should be pointed up and back. Keep your body stable as you slowly lower the dumbbell back to the floor. Then repeat on the other side.',
        difficulty: 'Advanced',
        images: '',
        description: 'Renegade row workout',
        group_id: 1,
        routine_id: 2,
    }
]

const seedExercise = () => Exercise.bulkCreate(exercisedata); 

module.exports = seedExercise;
